# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Code\LocalProjects\GitCodeChange\UI\Git_code_change_select_files.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Selectfiles(object):
    def setupUi(self, Selectfiles):
        Selectfiles.setObjectName("Selectfiles")
        Selectfiles.resize(768, 612)
        self.widget = QtWidgets.QWidget(Selectfiles)
        self.widget.setGeometry(QtCore.QRect(10, 20, 77, 141))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_select_all = QtWidgets.QPushButton(self.widget)
        self.pushButton_select_all.setObjectName("pushButton_select_all")
        self.verticalLayout.addWidget(self.pushButton_select_all)
        self.pushButton_select_modify = QtWidgets.QPushButton(self.widget)
        self.pushButton_select_modify.setObjectName("pushButton_select_modify")
        self.verticalLayout.addWidget(self.pushButton_select_modify)
        self.pushButton_select_add = QtWidgets.QPushButton(self.widget)
        self.pushButton_select_add.setObjectName("pushButton_select_add")
        self.verticalLayout.addWidget(self.pushButton_select_add)
        self.pushButton_select_delete = QtWidgets.QPushButton(self.widget)
        self.pushButton_select_delete.setObjectName("pushButton_select_delete")
        self.verticalLayout.addWidget(self.pushButton_select_delete)
        self.pushButton_deselect_all = QtWidgets.QPushButton(self.widget)
        self.pushButton_deselect_all.setObjectName("pushButton_deselect_all")
        self.verticalLayout.addWidget(self.pushButton_deselect_all)

        self.retranslateUi(Selectfiles)
        QtCore.QMetaObject.connectSlotsByName(Selectfiles)

    def retranslateUi(self, Selectfiles):
        _translate = QtCore.QCoreApplication.translate
        Selectfiles.setWindowTitle(_translate("Selectfiles", "Select Files"))
        self.pushButton_select_all.setText(_translate("Selectfiles", "Select All"))
        self.pushButton_select_modify.setText(_translate("Selectfiles", "Select Modify"))
        self.pushButton_select_add.setText(_translate("Selectfiles", "Select Add"))
        self.pushButton_select_delete.setText(_translate("Selectfiles", "Select Delete"))
        self.pushButton_deselect_all.setText(_translate("Selectfiles", "Deselect All"))
