# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Code\LocalProjects\GitCodeChange\UI\Git_code_change_how_to_use.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Howtoused(object):
    def setupUi(self, Howtoused):
        Howtoused.setObjectName("Howtoused")
        Howtoused.resize(425, 668)
        self.buttonBox = QtWidgets.QDialogButtonBox(Howtoused)
        self.buttonBox.setGeometry(QtCore.QRect(60, 550, 351, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Howtoused)
        self.buttonBox.accepted.connect(Howtoused.accept) # type: ignore
        self.buttonBox.rejected.connect(Howtoused.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Howtoused)

    def retranslateUi(self, Howtoused):
        _translate = QtCore.QCoreApplication.translate
        Howtoused.setWindowTitle(_translate("Howtoused", "How to use"))
